# Cloudflare Pages配置文件

name = "adminsystem"
main = "./worker/adminsystem/adminsystem.js"
compatibility_date = "2023-10-30"

# 配置D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "liubaocha-db"
database_id = "440ba7f7-c29c-406c-95ba-ebb2b6aa98cd"