# worker/adminsystem/wrangler.toml
name = "adminsystem"
main = "./adminsystem.js"
compatibility_date = "2025-05-06"

# 配置D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "liubaocha-db"
database_id = "440ba7f7-c29c-406c-95ba-ebb2b6aa98cd"

# 配置R2存储桶绑定
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "liubaotea"

# 环境变量
[vars]
R2_DOMAIN = "r2liubaotea.liubaotea.online"